[build]
  publish = "public"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/index.html"
  [headers.values]
    cache-control = "no-cache"
